# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import servicioimagen_pb2 as servicioimagen__pb2


GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servicioimagen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioProcesamientoImagenStub(object):
    """Servicio para procesamiento distribuido de imágenes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcesarImagen = channel.unary_unary(
                '/servicioimagen.ServicioProcesamientoImagen/ProcesarImagen',
                request_serializer=servicioimagen__pb2.SolicitudImagen.SerializeToString,
                response_deserializer=servicioimagen__pb2.RespuestaImagen.FromString,
                _registered_method=True)
        self.VerificarSalud = channel.unary_unary(
                '/servicioimagen.ServicioProcesamientoImagen/VerificarSalud',
                request_serializer=servicioimagen__pb2.SolicitudVerificacionSalud.SerializeToString,
                response_deserializer=servicioimagen__pb2.RespuestaVerificacionSalud.FromString,
                _registered_method=True)
        self.ObtenerMetricas = channel.unary_unary(
                '/servicioimagen.ServicioProcesamientoImagen/ObtenerMetricas',
                request_serializer=servicioimagen__pb2.SolicitudMetricas.SerializeToString,
                response_deserializer=servicioimagen__pb2.RespuestaMetricas.FromString,
                _registered_method=True)


class ServicioProcesamientoImagenServicer(object):
    """Servicio para procesamiento distribuido de imágenes
    """

    def ProcesarImagen(self, request, context):
        """Enviar imagen para procesamiento con transformaciones
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarSalud(self, request, context):
        """Verificar estado del nodo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerMetricas(self, request, context):
        """Obtener métricas del nodo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioProcesamientoImagenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcesarImagen': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcesarImagen,
                    request_deserializer=servicioimagen__pb2.SolicitudImagen.FromString,
                    response_serializer=servicioimagen__pb2.RespuestaImagen.SerializeToString,
            ),
            'VerificarSalud': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarSalud,
                    request_deserializer=servicioimagen__pb2.SolicitudVerificacionSalud.FromString,
                    response_serializer=servicioimagen__pb2.RespuestaVerificacionSalud.SerializeToString,
            ),
            'ObtenerMetricas': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerMetricas,
                    request_deserializer=servicioimagen__pb2.SolicitudMetricas.FromString,
                    response_serializer=servicioimagen__pb2.RespuestaMetricas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servicioimagen.ServicioProcesamientoImagen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servicioimagen.ServicioProcesamientoImagen', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioProcesamientoImagen(object):
    """Servicio para procesamiento distribuido de imágenes
    """

    @staticmethod
    def ProcesarImagen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servicioimagen.ServicioProcesamientoImagen/ProcesarImagen',
            servicioimagen__pb2.SolicitudImagen.SerializeToString,
            servicioimagen__pb2.RespuestaImagen.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerificarSalud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servicioimagen.ServicioProcesamientoImagen/VerificarSalud',
            servicioimagen__pb2.SolicitudVerificacionSalud.SerializeToString,
            servicioimagen__pb2.RespuestaVerificacionSalud.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerMetricas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servicioimagen.ServicioProcesamientoImagen/ObtenerMetricas',
            servicioimagen__pb2.SolicitudMetricas.SerializeToString,
            servicioimagen__pb2.RespuestaMetricas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
